### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by heshriti** [CharlesSkelton/studio#17]
Hi Charles.

Is it possible to customize the font type/size in the editor ?

**Comment by CharlesSkelton** [comment]
if my memory serves me correctly, in $HOME/.studioforkdb/studio.properties
there are 2 font related entries
font.size=14
font.name=Monospaced

these cannot be changed directly from within studio. First exit studio, and then use an editor such as vi to change them to your liking. You can list available java fonts via

$ cat ListJavaFonts.java
import java.awt.GraphicsEnvironment;
public class ListJavaFonts{
  public static void main(String[] args){
    String fonts[]=GraphicsEnvironment.getLocalGraphicsEnvironment().getAvailableFontFamilyNames();
    for(int i=0;i<fonts.length;i++)
      System.out.println(fonts[i]);
  }
}
$ javac ListJavaFonts.java
$ java -cp . ListJavaFonts

**Comment by heshriti** [comment]
Is it possible to change the table view fonts?
Specifically, I'd like to set the font family where zero are "slashed" or "open", as opposed to "dotted zeroes" which is what I have now.

I tried to change the Config. Java:
as follows:

String name = p.getProperty("font.name", "Inconsolata");
int  size = Integer.parseInt(p.getProperty("font.size","14"));

That didn't really change the table view font.

**Comment by heshriti** [comment]
Ok, Got it.

It is actually in the other file:
src/studio/core/Studio.java

UIManager.put("Table.font",new javax.swing.plaf.FontUIResource("Inconsolata",Font.PLAIN,UIManager.getFont("Table.font").getSize()));

Not sure I like it though.. But at least it's possible to customize.

Thank you..
